### ISSUE TITLE
Try some styled-components, or any other css-in-js approach

### ISSUE THREAD

**Issue by augustolazaro** [matheusmonte/entria#1]
We are a big fan of [styled-components](https://www.styled-components.com/) here in Entria. You may give this a try. Css-in-js is a great approach to make your components more reusable and context free.

**Comment by matheusmonte** [comment]
Thanks for the tip, I will try to change it on the next days

**Comment by matheusmonte** [comment]
The styled-component was added to the project and all .css files were remove from components
